# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/perf/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/qcom/perf

PRODUCT_COPY_FILES += \
    vendor/qcom/perf/proprietary/system_ext/etc/init/perfservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/perfservice.rc \
    vendor/qcom/perf/proprietary/system_ext/etc/init/qspmsvc.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/qspmsvc.rc \
    vendor/qcom/perf/proprietary/system_ext/etc/perf/wlc_model.tflite:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/perf/wlc_model.tflite \
    vendor/qcom/perf/proprietary/system_ext/etc/permissions/privapp-permissions-com.qualcomm.qti.performancemode.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-com.qualcomm.qti.performancemode.xml \
    vendor/qcom/perf/proprietary/system_ext/etc/seccomp_policy/perfservice.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/perfservice.policy \
    vendor/qcom/perf/proprietary/vendor/etc/init/poweropt-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/poweropt-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/init/vendor.qti.hardware.iop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.iop@2.0-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.2-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/init/vendor.qti.memory.pasrmanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.memory.pasrmanager@1.0-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/init/vendor.qti.psiclient@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.psiclient@1.0-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/init/vendor.qti.qspmhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.qspmhal@1.0-service.rc \
    vendor/qcom/perf/proprietary/vendor/etc/pwr/PowerFeatureConfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PowerFeatureConfig.xml \
    vendor/qcom/perf/proprietary/vendor/etc/pwr/VideoPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VideoPowerOptFeature.xml \
    vendor/qcom/perf/proprietary/vendor/etc/seccomp_policy/qspm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qspm.policy

PRODUCT_PACKAGES += \
    vendor.qti.hardware.perf2-V1-ndk \
    vendor.qti.hardware.servicetracker@1.2-impl \
    vendor.qti.memory.pasrmanager@1.0-impl \
    libpasrutils \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libpowercore \
    libqti-iopd-client \
    libqti-iopd \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libqti-utils \
    libskewknob \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0-vendor \
    vendor.qti.hardware.perf@2.0-vendor \
    vendor.qti.hardware.perf@2.1-vendor \
    vendor.qti.hardware.perf@2.2-vendor \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    vendor.qti.power.pasrmanager@1.0 \
    vendor.qti.qspmhal@1.0-impl \
    vendor.qti.qspmhal@1.0-vendor \
    libadaptlaunch \
    libappclassifier \
    libgameoptfeature \
    libgplaf \
    liblearningmodule \
    liblmutils-ns \
    libmemperfd \
    libmeters-ns \
    libmeters \
    libpowercallback \
    libprekill \
    libreffeature \
    libsplh \
    libbeluga \
    libcomposerextn.qti \
    libdolphin \
    liblayerext.qti \
    libpenguin \
    libpenguin_impl \
    libqape.qti \
    libqspm-mem-utils \
    libqspmsvc \
    libqti-at \
    libqti-iopd-client_system \
    libqti-perfd-client_system \
    libqti_performance \
    libqti_workloadclassifiermodel \
    libskewknob_system \
    libsmomoconfig.qti \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.limits@1.0 \
    vendor.qti.hardware.limits@1.1 \
    vendor.qti.hardware.perf@2.0 \
    vendor.qti.hardware.perf@2.1 \
    vendor.qti.hardware.perf@2.2 \
    vendor.qti.hardware.perf@2.3 \
    vendor.qti.qspmhal-V1-ndk \
    vendor.qti.qspmhal@1.0 \
    pasrservice \
    PowerSaveMode \
    workloadclassifier \
    PerformanceMode \
    QPerformance \
    QXPerformance \
    UxPerformance \
    vendor.qti.hardware.servicetracker@1.2-service.xml \
    vendor.qti.memory.pasrmanager@1.0-service.xml \
    vendor.qti.hardware.iop@2.0-service \
    vendor.qti.hardware.perf@2.2-service \
    vendor.qti.hardware.servicetracker@1.2-service \
    vendor.qti.memory.pasrmanager@1.0-service \
    vendor.qti.psiclient@1.0-service \
    msm_irqbalance \
    poweropt-service \
    vendor.qti.qspmhal@1.0-service \
    perfservice \
    qspmsvc
